### ISSUE TITLE
whereis example probably will not work on mac

### ISSUE THREAD

**Issue by ilyash-b** [alexst07/shell-plus-plus#2]
https://github.com/alexst07/shell-plus-plus#check-if-a-command-exists

I did not run on Mac but since the output of `whereis` is different on Linux and Mac, I assume the example would be broken on Mac:

```
# Mac
$ whereis ls
/bin/ls
$ whereis no-such-prog
(no output at all)

# Linux
$ whereis ls
ls: /bin/ls /usr/share/man/man1/ls.1.gz
$ whereis no-such-prog
no-such-prog:
```

I would consider `which`. It works the same on Mac and Linux and uses exit code to convey whether the command was found.

**Comment by alexst07** [comment]
Thanks for the feedback!
At the moment as it is still in the development stage I haven't tested it often on other platforms, but I will begin to test more in other OS than Linux. It would not even be so complicated to support even for Windows.
